name: build-and-release

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Removing sources.jar
        run: rm -rf build/libs/*sources.jar
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
      # Only publish when a version tag is pushed
      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: build/libs/*.jar

      - name: Parsing version info
        if: startsWith(github.ref, 'refs/tags/')
        id: version
        run: |
          GAME_VERSION="${GITHUB_REF_NAME%%-*}"
          echo "game_version=$GAME_VERSION" >> "$GITHUB_OUTPUT"

      - name: Publish to Modrinth
        if: startsWith(github.ref, 'refs/tags/')
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: dZhnUIjT
          version: ${{ github.ref_name }}
          loaders: fabric
          game-versions: ${{ steps.version.outputs.game_version }}
          files: build/libs/ibcarpet-${{ github.ref_name }}.jar
