name: Release Published Workflow to Modrinth

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: version
        run: |
          GAME_VERSION="${GITHUB_REF_NAME%%-*}"
          echo "game_version=$GAME_VERSION" >> "$GITHUB_OUTPUT"
      - uses: cloudnode-pro/modrinth-publish@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: IBCarpet
          version: ${{ github.event.release.tag_name }}
          loaders: fabric
          game-versions: ${{ steps.version.outputs.version }}
          files: build/libs/IBCarpet-${{ github.event.release.tag_name }}.jar
